apiVersion: v1
kind: Namespace
metadata:
  name: eck
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: eck
spec:
  version: 9.2.2
  nodeSets:
    - name: default
      count: 3
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: eck
spec:
  version: 9.2.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kibana
  namespace: eck
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kibana.local`)
      kind: Rule
      services:
        - name: kibana-kb-http
          port: 5601
          scheme: https
          serversTransport: kibana-transport
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: kibana-transport
  namespace: eck
spec:
  insecureSkipVerify: true
