# Vagrantfile - 3 VMs zeradas para instalação manual do kubeadm
# Objetivo de ter as VMs acessíveis via SSH, mas para instalação manual do kubeadm e com recursos mínimos sem precisar se preocupar com SO.
# Isso facilita criar e destruir infra local e focar no aprendizado do Kubernetes.

PUBKEY_PATH = File.expand_path("~/.ssh/id_rsa.pub")
PUBKEY      = File.exist?(PUBKEY_PATH) ? File.read(PUBKEY_PATH).strip : ""

if PUBKEY.empty?
  raise "Nao encontrei sua chave publica em: #{PUBKEY_PATH}. Ajuste o PUBKEY_PATH."
end

Vagrant.configure("2") do |config|
  config.vm.box = "lab/debian12-20gb"
  config.ssh.insert_key = false
  config.vm.synced_folder "../src", "/scripts", disabled: true

  nodes = [
    { name: "source", ip: "192.168.56.22", mem: 6144, cpu: 3 },
    #{ name: "failback", ip: "192.168.56.23", mem: 2048, cpu: 2 },
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |vm|
      vm.vm.hostname = node[:name]
      vm.vm.network "private_network", ip: node[:ip]

      vm.vm.provider "virtualbox" do |vb|
        vb.name = "#{node[:name]}"
        vb.memory = node[:mem]
        vb.cpus = node[:cpu]
      end

      # Provisionamento minimo: só adiciona a sua chave publica
      vm.vm.provision "shell", privileged: true, inline: <<-SHELL
        set -e

        USER=vagrant
        HOME_DIR=/home/$USER
        SSH_DIR=$HOME_DIR/.ssh
        AUTH_KEYS=$SSH_DIR/authorized_keys

        mkdir -p "$SSH_DIR"
        chmod 700 "$SSH_DIR"
        touch "$AUTH_KEYS"
        chmod 600 "$AUTH_KEYS"
        chown -R "$USER:$USER" "$SSH_DIR"
        echo "127.0.1.1 #{node[:name]}" >> /etc/hosts

        KEY='#{PUBKEY.gsub("'", %q('"'"'))}'

        # adiciona somente se ainda nao existir
        grep -qxF "$KEY" "$AUTH_KEYS" || echo "$KEY" >> "$AUTH_KEYS"

        # instala pacotes basicos
        apt-get update
        apt-get install -y vim git curl wget net-tools iputils-ping dnsutils unzip
        mkdir -p /scripts
        chmod 777 /scripts
        cd /scripts
        #isntala aws cli
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install
        aws --version
        
      SHELL
    end
  end


end

